//! Custom `KeyProvider` end-to-end example: source the `unlock_key` from a
//! secrets backend that returns the material bytes to the process (vault,
//! secrets manager, network KMS) by implementing the trait by hand on the
//! typed edge, instead of using a built-in provider. For an HSM that keeps
//! its wrapping key in hardware, see `envelope_provider.rs`.
//!
//! This is the runnable form of the custom-provider snippet in
//! `docs/DEPLOYMENT.md`: `UnlockMaterial::new` validates and normalizes the
//! fetched bytes (rejects empty, strips at most one trailing newline) and
//! `UnlockKey::derive` runs the shared External-tier KDF, so the provider
//! reaches the same key the build sealed under with no encoding step.
//!
//! ```sh
//! # 1. Mint unlock material and seal the build under it (External tier).
//! KEY=$(cargo run -q -p litmask-cli -- keygen)
//! LITMASK_UNLOCK_KEY="$KEY" \
//!     cargo build --release --features provider-examples --example custom_provider
//! # 2. Run against the SAME material your "vault" hands back.
//! LITMASK_UNLOCK_KEY="$KEY" ./target/release/examples/custom_provider
//! # prints the decrypted Wilde quote at runtime
//! ```
//!
//! Run the prebuilt binary directly, not `cargo run` — under the release
//! profile that reruns `build.rs`, regenerating the seed and resealing the
//! wrapper, so a fresh build no longer matches the key you sealed under.
//! See `hello_world.rs`.
//!
//! Verify the masked plaintext is absent from `.rodata` the same way
//! `hello_world.rs` does:
//!
//! ```sh
//! strings target/release/examples/custom_provider | grep "rarely pure"
//! # (no output — the plaintext is absent from the binary)
//! ```
//!
//! The fixture is Oscar Wilde (d. 1900, US public domain); the words
//! "rarely pure and never simple" are not generated by std or our
//! dependencies, so a successful grep there reliably indicates a real
//! leak. Each example in this directory masks a different public-domain
//! quip.

use litmask::{KeyError, KeyProvider, UnlockKey, UnlockMaterial, init, mask};

/// Stand-in for a real secrets backend: holds the sealed unlock material
/// fetched from your vault / secrets manager / KMS. Any non-empty bytes work; empty
/// material surfaces as `KeyError::InvalidFormat` through the `?` in
/// `unlock_key` (the `From<EmptyMaterial>` conversion), so an unpopulated
/// secret fails closed rather than deriving a bogus key.
struct VaultProvider(Vec<u8>);

impl KeyProvider for VaultProvider {
    fn unlock_key(&self) -> Result<UnlockKey, KeyError> {
        Ok(UnlockKey::derive(UnlockMaterial::new(&self.0)?))
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // In a real deployment these bytes come from your vault at startup.
    // Here the build was sealed under `LITMASK_UNLOCK_KEY`, so read the
    // same value back as the material the "vault" hands us.
    let material = std::env::var("LITMASK_UNLOCK_KEY")?.into_bytes();
    init!(VaultProvider(material))?;
    println!(
        "{}",
        mask!("The truth is rarely pure and never simple. — Oscar Wilde"),
    );
    Ok(())
}
