//! HSM-envelope `KeyProvider` example: the unlock material is **not**
//! embedded in the clear and **not** read from the environment at runtime.
//! Instead a *wrapped* (encrypted) copy of it is stored in the binary, and
//! at startup a hardware security module (HSM) unwraps it — the DEK/KEK
//! envelope pattern applied to litmask's External tier.
//!
//! Roles:
//!   * KEK — the wrapping key. Lives inside the HSM, never leaves hardware.
//!   * DEK — the unlock material (`UnlockMaterial`) the build sealed under.
//!   * wrapped DEK — `ENC_kek(material)`, embedded here as
//!     [`WRAPPED_UNLOCK_MATERIAL`]. This is the "encrypted unlock key stored
//!     in the binary".
//!
//! Runtime flow: `provider.unlock_key()` hands the wrapped blob to the HSM,
//! the HSM decrypts it internally and returns the plaintext material, and
//! `UnlockKey::derive` runs the shared External-tier KDF — reaching the same
//! key the build sealed under, with no plaintext secret ever stored at rest.
//!
//! What the HSM buys you: the wrapped blob is inert without an authenticated
//! call to the HSM, so copying the binary is not enough to unlock it. The
//! HSM enforces access control, audit, rate-limiting, and revocation on
//! every unwrap. What it does NOT buy you: litmask's AEAD runs in-process,
//! so the unwrapped material — and the derived `unlock_key` and `mask_key` —
//! still transit process memory. This is defense-in-depth on the *key at
//! rest*, not a promise that key bytes never enter RAM.
//!
//! ```sh
//! # The build seals under the DEMO material below (its plaintext);
//! # the embedded blob unwraps to exactly that.
//! LITMASK_UNLOCK_KEY="envelope-demo-unlock-material-do-not-reuse" \
//!     cargo run --features provider-examples --example envelope_provider
//! # prints the decrypted Franklin quote at runtime
//! ```
//!
//! Verify the masked plaintext is absent from `.rodata` the same way
//! `hello_world.rs` does:
//!
//! ```sh
//! strings target/release/examples/envelope_provider | grep "parents of security"
//! # (no output — the plaintext is absent from the binary)
//! ```
//!
//! The fixture is Benjamin Franklin (d. 1790, US public domain); the words
//! "parents of security" are not generated by std or our dependencies, so a
//! successful grep there reliably indicates a real leak.

use litmask::{KeyError, KeyProvider, UnlockKey, UnlockMaterial, init, mask};

/// `ENC_kek(material)` — a wrapped copy of the unlock material, embedded in
/// the binary. Inert on its own: only the HSM holding the KEK can turn these
/// bytes back into the material. Its correctness is pinned executably by
/// `scripts/test-examples.sh`: a wrong blob unwraps to the wrong material, so
/// `init!(provider)` fails to open the wrapper and the binary exits non-zero,
/// failing the script's `set -e` run.
const WRAPPED_UNLOCK_MATERIAL: &[u8] = &[
    0x68, 0x7a, 0x6d, 0x47, 0x45, 0x5f, 0x47, 0x5b, 0x68, 0x28, 0x36, 0x37, 0x0e, 0x45, 0x1a, 0x18,
    0x11, 0xeb, 0xe8, 0xf9, 0xb4, 0xcd, 0xc6, 0xda, 0xd0, 0xce, 0xaa, 0xab, 0xbd, 0xf5, 0xbb, 0x89,
    0x20, 0x7a, 0x74, 0x56, 0x04, 0x42, 0x52, 0x4b, 0x36, 0x29,
];

/// Stand-in for a real HSM. A production implementation calls out to
/// PKCS#11 / a cloud KMS unwrap endpoint; the KEK never leaves the device.
///
/// This stub holds the KEK as a compile-time constant purely so the example
/// is self-contained and reproducible. That concession also erases the
/// security benefit — an attacker with the binary would have both the
/// wrapped blob and its unwrapping key. The whole point of a real HSM is that
/// the KEK is unreachable, which is why the wrapped blob alone is worthless.
/// The XOR below is deliberately NOT a cipher; it stands in for the HSM's
/// authenticated decryption and nothing more.
struct StubHsm {
    kek: [u8; 32],
}

impl StubHsm {
    /// Where a real deployment opens the PKCS#11 session / KMS client.
    fn connect() -> Self {
        Self {
            kek: [
                0x0d, 0x14, 0x1b, 0x22, 0x29, 0x30, 0x37, 0x3e, 0x45, 0x4c, 0x53, 0x5a, 0x61, 0x68,
                0x6f, 0x76, 0x7d, 0x84, 0x8b, 0x92, 0x99, 0xa0, 0xa7, 0xae, 0xb5, 0xbc, 0xc3, 0xca,
                0xd1, 0xd8, 0xdf, 0xe6,
            ],
        }
    }

    /// Unwrap the embedded blob back to the plaintext unlock material. In a
    /// real HSM this decryption happens inside the device and the KEK is
    /// never exposed to this process.
    fn unwrap(&self, wrapped: &[u8]) -> Vec<u8> {
        wrapped
            .iter()
            .enumerate()
            .map(|(i, b)| b ^ self.kek[i % self.kek.len()])
            .collect()
    }
}

/// Holds a live HSM handle and the wrapped material. `unlock_key` performs
/// the unwrap-then-derive at `init!` time.
struct EnvelopeProvider {
    hsm: StubHsm,
    wrapped: &'static [u8],
}

impl KeyProvider for EnvelopeProvider {
    fn unlock_key(&self) -> Result<UnlockKey, KeyError> {
        let material = self.hsm.unwrap(self.wrapped);
        // `UnlockMaterial::new` rejects empty material (fail-closed) and
        // applies the same normalization every External channel uses, so the
        // unwrapped bytes reach the key the build sealed under.
        Ok(UnlockKey::derive(UnlockMaterial::new(&material)?))
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let provider = EnvelopeProvider {
        hsm: StubHsm::connect(),
        wrapped: WRAPPED_UNLOCK_MATERIAL,
    };
    init!(provider)?;
    println!(
        "{}",
        mask!("Distrust and caution are the parents of security. — Benjamin Franklin"),
    );
    Ok(())
}
