//! `FileProvider` end-to-end example: source the `unlock_key` from a
//! filesystem path instead of an environment variable.
//!
//! ```sh
//! # 1. Mint unlock material and seal the build under it (External tier).
//! KEY=$(cargo run -q -p litmask-cli -- keygen)
//! LITMASK_UNLOCK_KEY="$KEY" \
//!     cargo build --release --features provider-examples --example file_provider
//! # 2. Write the SAME material to a key file and run against it.
//! printf '%s' "$KEY" > /tmp/litmask_unlock.key
//! LITMASK_UNLOCK_KEY_FILE=/tmp/litmask_unlock.key \
//!     ./target/release/examples/file_provider
//! # prints the decrypted Wilde quote at runtime
//! ```
//!
//! Run the prebuilt binary directly, not `cargo run` — under the release
//! profile that reruns `build.rs`, regenerating the seed and resealing the
//! wrapper, so a fresh build no longer matches the key you sealed under.
//! See `hello_world.rs`.
//!
//! Verify the masked plaintext is absent from `.rodata` the same way
//! `hello_world.rs` does:
//!
//! ```sh
//! strings target/release/examples/file_provider | grep "except temptation"
//! # (no output — the plaintext is absent from the binary)
//! ```
//!
//! The fixture is Oscar Wilde (d. 1900, US public domain); the words
//! "except temptation" are not generated by std or our dependencies,
//! so a successful grep there reliably indicates a real leak. Each
//! example in this directory masks a different public-domain quip.

use litmask::{FileProvider, init, mask};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // `FileProvider::new(path)` reads the file bytes as raw key
    // material of any length and derives the `unlock_key` via the
    // shared KDF — the same normalization the env channel applies, so
    // the key file just holds the same material the build was sealed
    // under, with no encoding step.
    // The `test-examples` script mints material with `litmask keygen`
    // and exports `LITMASK_UNLOCK_KEY` to the example's environment. To
    // keep this example self-contained when run via `cargo run
    // --example file_provider`, fall back to writing that env-var value
    // into a temp file and pointing the provider at it.
    let path = if let Ok(p) = std::env::var("LITMASK_UNLOCK_KEY_FILE") {
        p
    } else {
        let key_b64 = std::env::var("LITMASK_UNLOCK_KEY")?;
        let mut tmp = std::env::temp_dir();
        tmp.push(format!(
            "litmask_file_provider_example_{}.key",
            std::process::id()
        ));
        std::fs::write(&tmp, &key_b64)?;
        tmp.to_string_lossy().into_owned()
    };

    init!(FileProvider::new(&path))?;
    println!(
        "{}",
        mask!("I can resist everything except temptation. — Oscar Wilde"),
    );
    Ok(())
}
