#!/usr/bin/env bash
# scripts/setup-dev.sh — bootstrap the local development environment.
#
# Most tools live in `shell.nix`; tools whose nix derivations are
# broken or version-mismatched are installed via `cargo install`
# below. Safe to re-run; each install step is idempotent.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v nix-shell >/dev/null 2>&1; then
    echo "litmask: setup-dev — nix-shell not on PATH" >&2
    echo "  hint: install Nix from https://nixos.org/download" >&2
    exit 1
fi

# Regenerate `rust-toolchain.toml` from `.tool-versions`. The toolchain
# file is a derived artifact — `.tool-versions` is the canonical
# source of the pinned Rust channel. Generating here means a single
# `.tool-versions` edit propagates atomically; check-tool-versions
# still enforces equality so any out-of-band edit is flagged.
rust_version=$(grep -E '^rust\s' .tool-versions | awk '{print $2}')
cat > rust-toolchain.toml <<EOF
# Auto-generated by scripts/setup-dev.sh from .tool-versions.
# Edit .tool-versions instead and re-run \`just setup\`.
[toolchain]
channel = "${rust_version}"
profile = "minimal"
components = ["clippy", "rustfmt", "llvm-tools"]
# \`thumbv7m-none-eabi\`: bare-metal target for \`just check-no-std\`.
# \`x86_64-pc-windows-gnu\`, \`aarch64-apple-darwin\`: cross targets for
# \`just check-cross\` (cargo check only, no linker required).
targets = [
  "thumbv7m-none-eabi",
  "x86_64-pc-windows-gnu",
  "aarch64-apple-darwin",
]
EOF

nix-shell --run '
    set -euo pipefail

    # The Rust toolchain is provided by rust-overlay inside the nix
    # shell (see shell.nix); entering the shell already materializes the
    # pinned channel from rust-toolchain.toml, so no rustup step here.

    # Tools whose nix derivations are broken or version-mismatched.
    install_cargo_tool() {
        local pkg="$1" ver="$2" actual
        actual=$(cargo "${pkg#cargo-}" --version 2>/dev/null | awk "{print \$2}") || true
        if [ "$actual" = "$ver" ]; then
            return
        fi
        echo "litmask: setup-dev — installing $pkg@$ver via cargo…"
        cargo install "$pkg" --version "$ver" --locked
    }

    llvm_cov_ver=$(awk "/^cargo-llvm-cov / {print \$2}" .tool-versions)
    install_cargo_tool cargo-llvm-cov "$llvm_cov_ver"

    semver_ver=$(awk "/^cargo-semver-checks / {print \$2}" .tool-versions)
    install_cargo_tool cargo-semver-checks "$semver_ver"

    # Authoritative match against `.tool-versions`; aborts on drift
    # so a misaligned nix-shell surfaces here instead of in CI.
    echo "litmask: setup-dev — verifying pinned tools…"
    just check-tool-versions

    echo "litmask: setup-dev — installing Node devDependencies for commitlint…"
    npm ci --no-audit --no-fund

    echo "litmask: setup-dev — installing git hooks via pre-commit…"
    pre-commit install --install-hooks \
        --hook-type pre-commit \
        --hook-type pre-push \
        --hook-type commit-msg

    echo "litmask: setup-dev — done."
'
