#!/usr/bin/env bash
# scripts/setup-dev.sh — bootstrap the local development environment.
#
# Every pinned tool comes from `shell.nix`; this script only generates
# `rust-toolchain.toml`, verifies the pins, and installs the things nix
# does not own (npm devDependencies, git hooks). Safe to re-run.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v nix-shell >/dev/null 2>&1; then
    echo "litmask: setup-dev — nix-shell not on PATH" >&2
    echo "  hint: install Nix from https://nixos.org/download" >&2
    exit 1
fi

# Regenerate `rust-toolchain.toml` from `.tool-versions`. The toolchain
# file is a derived artifact — `.tool-versions` is the canonical
# source of the pinned Rust channel. Generating here means a single
# `.tool-versions` edit propagates atomically; check-tool-versions
# still enforces equality so any out-of-band edit is flagged.
rust_version=$(grep -E '^rust\s' .tool-versions | awk '{print $2}')
cat > rust-toolchain.toml <<EOF
# Auto-generated by scripts/setup-dev.sh from .tool-versions.
# Edit .tool-versions instead and re-run \`just setup\`.
[toolchain]
channel = "${rust_version}"
profile = "minimal"
components = ["clippy", "rustfmt", "llvm-tools"]
# \`thumbv7m-none-eabi\`: bare-metal target for \`just check-no-std\`.
# \`x86_64-pc-windows-gnu\`, \`aarch64-apple-darwin\`: cross targets for
# \`just check-cross\` (cargo check only, no linker required).
targets = [
  "thumbv7m-none-eabi",
  "x86_64-pc-windows-gnu",
  "aarch64-apple-darwin",
]
EOF

nix-shell --run '
    set -euo pipefail

    # The Rust toolchain is provided by rust-overlay inside the nix
    # shell (see shell.nix); entering the shell already materializes the
    # pinned channel from rust-toolchain.toml, so no rustup step here.

    # cargo-llvm-cov and cargo-semver-checks used to be `cargo install`ed
    # here because the pinned nixpkgs shipped the wrong versions.
    # shell.nix now pins both to upstream release binaries, so nix owns
    # every tool in `.tool-versions` and there is nothing to install.

    # Authoritative match against `.tool-versions`; aborts on drift
    # so a misaligned nix-shell surfaces here instead of in CI.
    echo "litmask: setup-dev — verifying pinned tools…"
    just check-tool-versions

    echo "litmask: setup-dev — installing Node devDependencies for commitlint…"
    npm ci --no-audit --no-fund

    echo "litmask: setup-dev — installing git hooks via pre-commit…"
    pre-commit install --install-hooks \
        --hook-type pre-commit \
        --hook-type pre-push \
        --hook-type commit-msg

    echo "litmask: setup-dev — done."
'
